set number
syntax on
set mouse=a
colorscheme atom-dark-256

call plug#begin()
Plug 'bling/vim-airline'
call plug#end()
let g:airline_powerline_fonts = 1
let g:airline#extensions#fbracnh#enabled = 1
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline#left_alt_sep = '|'
